# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c287be1d5532465d70b5dcdd14e9077221f7ba2d5a0194e81e1909764fc5d85f45e52d54b7ac63a71fe85f819a7f876f923fedf8a30653bee6d6b1b7948d4dd

test:
  secret_key_base: 1616d232ade0dacbe5ab8416c4ac2f6d13ff81edf5e4ba417d97f327b85310775c57b7938b5c51d07bde07cd0f93a45e87f26ae8d85727cf4fb20983bcdfef0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
